### ISSUE TITLE
Switch to XCTest

### ISSUE THREAD

**Issue by pronebird** [Kabal/Operative#12]
Is there any particular reason why you use Expecta? I bet it would be much easier to write XCTests and I believe more people are familiar with it.

**Comment by ghost** [comment]
No real reason. This is actually the first time i've ever made my own cocoapod and it asked if i wanted to include it and i was like sure why not.

I think I actually prefer XCTest too...

**Comment by pronebird** [comment]
PR #18 adds support for XCTest.
