### ISSUE TITLE
Crash in setState:

### ISSUE THREAD

**Issue by pronebird** [Kabal/Operative#13]
From time to time I see a crash in `setState:`. For example state = `OPOperationStateExecuting` and then I receive `OPOperationStateReady` from condition. I am not able to find out why yet. I use pretty arbitrary threads to add new ops to group operation, that maybe the cause.

**Comment by ghost** [comment]
Hmm Apple says that NSOperationQueue should be thread safe so it might be a problem in Operative's code.

"It is safe to use a single NSOperationQueue object from multiple threads without creating additional locks to synchronize access to that object." - from https://developer.apple.com/library/ios/documentation/Cocoa/Reference/NSOperationQueue_class/

**Comment by pronebird** [comment]
I'll keep you posted. I have spotted one dangling dependent operation that I forgot to add to operation queue :grin: so that could be the cause of all my troubles. I don't see this issue anymore but I also re-factored quite a lot of my code, so maybe there is an edge case that I worked around...

**Comment by pronebird** [comment]
Closing because I do not experience this anymore and I believe I had this issue because some of my ops was not in the queue but was referenced in dependencies and probably cancelled at some point.
