### ISSUE TITLE
Retain cycle somewhere in OPOperationConditionMutuallyExclusive

### ISSUE THREAD

**Issue by pronebird** [Kabal/Operative#14]
Exclusive operations never being released. I checked on Example app and OPAlertOperation does not get released either even after it prints that operation group completed.

I made a test operation which does not do anything at all and it's never being released either.

``` objc
@interface TestOperation : OPOperation
@end

@implementation TestOperation

- (instancetype)init {
    if(self = [super init]) {
        [self addCondition:[OPOperationConditionMutuallyExclusive mutuallyExclusiveWith:[self class]]];
    }
    return self;
}

- (void)dealloc {
    NSLog(@"%s", __PRETTY_FUNCTION__);
}

- (void)execute {
    NSLog(@"Run operation");
    [self finish];
}

@end
```

`deinit` in Swift implementation works though.

**Comment by pronebird** [comment]
Well I guess I busted it in my PR.

**Comment by ghost** [comment]
Closing because #21 merged
