### ISSUE TITLE
OPRemoteNotificationPermissionOperation never calls finish

### ISSUE THREAD

**Issue by pronebird** [Kabal/Operative#48]
Once `didReceiveRemoteRegistrationResponse` received we should call `[self finish];` to complete the operation. Currently finish is not being called.

**Comment by colinmcardell** [comment]
Multiple commits. Sorry about that. I was stomping on my own changes. `d1a1486` is the appropriate commit. I will make a PR.

**Comment by pronebird** [comment]
@colinmcardell thanks for fixing this!

**Comment by colinmcardell** [comment]
For sure. Good call!

**Comment by colinmcardell** [comment]
Resolved with 4e33fac254d7209b65f395a6d8ea50fc2493501c. Closing..
