### ISSUE TITLE
Stale operations in certain % of cases

### ISSUE THREAD

**Issue by pronebird** [Kabal/Operative#51]
Hi,

I have a very interesting bug here. I _CAN_ reproduce it with unit tests but with less success. Although it's easier to reproduce in Example app that we have!

So here is a very simple operation that calls finish on main thread.

``` objc
#import <XCTest/XCTest.h>
#import <Operative/Operative.h>

@interface OPOperationQueue (SharedQueue)

+ (instancetype)sharedQueue;

@end

@implementation OPOperationQueue (SharedQueue)

+ (instancetype)sharedQueue {
    static id queue;
    static dispatch_once_t onceToken;

    dispatch_once(&onceToken, ^{
        queue = [[self alloc] init];
    });

    return queue;
}

@end

@interface XCMaintenanceOperation : OPOperation
@end

@implementation XCMaintenanceOperation

- (instancetype)init
{
    self = [super init];
    if(!self) {
        return nil;
    }

    [self addCondition:[OPOperationConditionMutuallyExclusive mutuallyExclusiveWith:[self class]]];

    return self;
}

- (void)execute
{
    NSLog(@"Finish operation.");

    dispatch_async(dispatch_get_main_queue(), ^{
        [self finish];
    });
}

@end

@interface Tests : XCTestCase

@end

@implementation Tests

- (void)testStaleOperations
{
    XCTestExpectation *expectation = [self expectationWithDescription:@"Wait for miracle"];

    NSMutableArray *operations = [[NSMutableArray alloc] init];

    OPBlockOperation *finishOperation = [[OPBlockOperation alloc] initWithMainQueueBlock:^{
        NSLog(@"*** DONE ***");

        [expectation fulfill];
    }];

    for(NSInteger i = 0; i < 500; i++)
    {
        XCMaintenanceOperation *op = [[XCMaintenanceOperation alloc] init];

        [finishOperation addDependency:op];

        [operations addObject:op];
    }

    [operations addObject:finishOperation];

    [[OPOperationQueue sharedQueue] addOperations:operations waitUntilFinished:NO];

    [self waitForExpectationsWithTimeout:10 handler:^(NSError * _Nullable error) {
        NSLog(@"Remaining Operations: %@", [[OPOperationQueue sharedQueue] debugDescription] );
    }];
}

@end
```

So I end up with `-[XCMaintenanceOperation release]: message sent to deallocated instance 0x7f8ca40c5440`.

Stack trace looks like a roll of all dependencies being released at once.

<img width="363" alt="screenshot 2016-04-07 00 42 36" src="https://cloud.githubusercontent.com/assets/704044/14336234/af6e36dc-fc59-11e5-9224-912f393411ed.png">

Very random bug, sometimes operations just freeze in certain state, e.g. Ready or any other and does not start. Then I have the entire queue of dangling ops.

```
<__NSArrayM 0x7f92f1ce7cb0>(
<XCMaintenanceOperation: 0x7f92f1835f70> (Ready),
<XCMaintenanceOperation: 0x7f92f1834840> (Pending),
<XCMaintenanceOperation: 0x7f92f1836530> (Pending),
<XCMaintenanceOperation: 0x7f92f1836800> (Pending),
<XCMaintenanceOperation: 0x7f92f1836ad0> (Pending),
<XCMaintenanceOperation: 0x7f92f1836d40> (Pending),
<XCMaintenanceOperation: 0x7f92f1836fb0> (Pending),
<XCMaintenanceOperation: 0x7f92f1837280> (Pending),
<XCMaintenanceOperation: 0x7f92f18374f0> (Pending),
<XCMaintenanceOperation: 0x7f92f18377c0> (Pending),
<XCMaintenanceOperation: 0x7f92f1837a30> (Pending),
<XCMaintenanceOperation: 0x7f92f1835260> (Pending),
<XCMaintenanceOperation: 0x7f92f1838040> (Pending),
<XCMaintenanceOperation: 0x7f92f18382b0> (Pending),
<XCMaintenanceOperation: 0x7f92f1838520> (Pending),
<XCMaintenanceOperation: 0x7f92f1838790> (Pending),
<XCMaintenanceOperation: 0x7f92f1838a00> (Pending),
<XCMaintenanceOperation: 0x7f92f1838c70> (Pending),
<XCMaintenanceOperation: 0x7f92f1838ee0> (Pending),
<XCMaintenanceOperation: 0x7f92f18391b0> (Pending),
<XCMaintenanceOperation: 0x7f92f1839480> (Pending),
<XCMaintenanceOperation: 0x7f92f1839750> (Pending),
<XCMaintenanceOperation: 0x7f92f18399c0> (Pending),
<XCMaintenanceOperation: 0x7f92f1839c30> (Pending)
)
```

Did you happen to stumble upon something like that? Everything worked fine until recently I first found dangling ops, then sometimes crash.

_Update:_

It's more consistently reproducible if you put the code above into Example app's viewDidLoad.

**Comment by colinmcardell** [comment]
Interesting. I have run into situations where things seem to hang in a specific state. I'm curious if the `@synchronized` lock on the getter and setter for `state` for `OPOperation` might be causing this. Mind pulling those out on your local and giving that test a run again?

**Comment by pronebird** [comment]
@colinmcardell seem to help to run my dummy code in Example app. I gotta test more. Besides, looking at https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/Operation.swift#L287

I think we are missing some synchronization for `isReady` and/or logic. I have to take a look at it closer.

**Comment by colinmcardell** [comment]
Ah. That would make sense. Yeah, keep me posted.

**Comment by pronebird** [comment]
@colinmcardell I tried to move or remove synchronized blocks and all that stuff. I even replaced them with NSLock and NSRecursiveLock the same way it's done in Operations. Same problem. I run thousands of operations, once in a while it snaps, and main and start are never being called. Operation remains frozen in Ready state.

Could you please take a look at this issue? Maybe I am missing something... I have this branch here where you can get a clue how I conduct testing:

https://github.com/pronebird/Operative/blob/fix/stale-operations-bug/Example/Operative/OPViewController.m

Also, you can pick up one of my recent PRs that adds debugDescription to operations which should let you inspect the operation guts from debugger console.

**Comment by pronebird** [comment]
I wrote test for Apple's Earthquakes – exactly the same problem.

``` swift
import UIKit

let sharedQueue = OperationQueue()

class TestOperation : Operation
{

    override func execute() {
        dispatch_async(dispatch_get_main_queue()) {
//            print("Finished.")
            self.finish()
        }
    }

}

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    // MARK: Properties

    var window: UIWindow?

    func applicationDidFinishLaunching(application: UIApplication) {
        cycle(1)
    }

    func cycle(take: Int)
    {
        var operations = [Operation]()

        let startOp = BlockOperation {
            print("Begin operations: Take \(take)")
        }

        let endOp = BlockOperation { [weak self] in
            print("End operations")

            if take < 10 {
                self?.cycle(take + 1)
            }
            else {
                print("This is it!")
            }
        }

        for _ in 1...40
        {
            let op = TestOperation()

            op.addDependency(startOp)

            endOp.addDependency(op)

            operations.append(op)
        }

        operations.append(startOp)
        operations.append(endOp)

        sharedQueue.addOperations(operations, waitUntilFinished: false)
    }

    // MARK: UIApplicationDelegate

    func application(application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: NSError) {
        RemoteNotificationCondition.didFailToRegister(error)
    }

    func application(application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
        RemoteNotificationCondition.didReceiveNotificationToken(deviceToken)
    }
}
```

Output in LLDB:

```
(lldb) po sharedQueue.operations
▿ 2 elements
  - [0] : <Earthquakes.TestOperation: 0x7ffcd86ef1b0> Ready
  ▿ [1] : <Earthquakes.BlockOperation: 0x7ffcd86eef60> Pending
```

I wonder if Operations has the same issue...

**Comment by pronebird** [comment]
Operations framework (swift) runs batches of 500 without a single crash. I ran about 50k ops without any issues. I'll be inspecting Operations framework and matching it against our codebase. It feels like we have concurrency issue and some of memory is being corrupted as a result.

**Comment by pronebird** [comment]
MutuallyExclusive condition kills Operations framework in the same fashion. I wonder if there is a KVO bug somewhere in NSOperationQueue...

**Comment by pronebird** [comment]
Operations has the same issue. Relevant issues:

https://github.com/danthorpe/Operations/issues/175
https://github.com/danthorpe/Operations/pull/180

**Comment by pronebird** [comment]
A week of my life in #52. Closing this and moving discussion to PR.
